Update 0-iamsomeoneelse

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,8 +1,16 @@
 #!/usr/bin/env bash
-# Runs whoami command as the user provided in argument
-if [ $# -eq 1 ]; then
+
+# Check if exactly one argument is passed
+if [ $# -ne 1 ]; then
+  echo "Usage: $0 <username>"
+  exit 1
+fi
+
+# Check if the user exists on the system
+if id "$1" &>/dev/null; then
+  # Run the whoami command as the user passed in the argument
   sudo -u "$1" whoami
 else
-  echo "Usage: $0 <username>"
+  echo "Error: User '$1' does not exist."
   exit 1
 fi
